version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-bot
    environment:
      - TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}
    volumes:
      - .:/app
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: telegram_bot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - bot
    ports:
      - "80:80"

volumes:
  postgres_data: